### ISSUE TITLE
What is difference between this and NCalc2 ?

### ISSUE THREAD

**Issue by mganley2000** [pitermarx/NCalc-Edge#1]
You have two different versions here in GitHub.  What is difference between NCalc-Edge and NCalc2? 
https://github.com/pitermarx/NCalc2

Thanks

**Comment by pitermarx** [comment]
In NCalc-edge i used the latest code in the original source and just updated a minor version on ANTLr. I'm using this version on my production code. NCalc2 has a newer (major)version of ANTLr and some newer .net features like dynamics. I dont use it yet on production.
I dont expect to do any changed in NCalc-Edge except for bug fixes

**Comment by pitermarx** [comment]
I dont expect to do any changed in NCalc-Edge except for bug fixes

—
Pedro Marques
