### ISSUE TITLE
Rounding last digit of calculations

### ISSUE THREAD

**Issue by swax** [pitermarx/NCalc-Edge#10]
Not sure if it should go here or in ncalc2, but my issue is when you do something like `2.000002 - 2.000001` you get `9.99999999695689E-07` when you should probably get something clean like `1E-06`

My current fix is to surround the basic calculations in Number.cs with 

```
    private static object RoundDouble(object value)
    {
        if (value is double)
             return Math.Round((double)value, 15);
         else
             return value;
    }
```

Maybe there is a better solution, but this does prevent the problem. Let me know if you're interested and I'll submit a pull request with tests.

**Comment by pitermarx** [comment]
I think this is the expected behaviour.
As you can see [in the wiki](https://github.com/pitermarx/NCalc-Edge/wiki/Values) the numeric values are floating point numbers.
What you are getting is the expected error on floating point operations.
This is how .net behaves.

**Comment by pitermarx** [comment]
[Just found this](http://0.30000000000000004.com/).
Closing
