### ISSUE TITLE
Support for Package Reference style of using NuGet Package

### ISSUE THREAD

**Issue by james1301** [pitermarx/NCalc-Edge#12]
Hi, just downloaded the latest Visual Studio with support for migrating .net projects from using packages.config to the new Package Reference style.

Getting a Compatibility issue with NCal-Edge of:

"The assembly 'lib\lib\NCalc.dll' will be ignored when the package is installed after migration."

And the same goes for the Antlr depdency Nuget it installs.

Firstly is this an issue? And secondly is it possible for this issue to be resolved in a new version of NCalc-Edge?

More about Package Reference migration process here: [https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#how-to-roll-back-to-packagesconfig](url)

Thanks,

James

**Comment by pitermarx** [comment]
It might be an issue but I'm not able to look into it right now. I haven't yet started using the new CSproj. If you have a solution let me know

**Comment by pitermarx** [comment]
I think the issue is that i'm publishing the package in \lib instead of \lib\net46

**Comment by james1301** [comment]
Yes sorry that is the issue I think. I am just using the new "Migrate packages.config to Package Reference" option in Visual Studio 15.7.

**Comment by pitermarx** [comment]
take a look at https://github.com/pitermarx/NCalc2 
it's completely *untested* at production but it's based on NCalc and it targets netstandard 2.0

**Comment by james1301** [comment]
NCalc2 sounds good, but don't think I can go for an untested solution. Will it be possible to sort this NuGet package out?

**Comment by pitermarx** [comment]
can you try this? https://ci.appveyor.com/project/pitermarx/ncalc-edge/build/artifacts
it seems to have the ncalc.dll inside the lib\net35 folder but it gives this warning
``
WARNING: Issue: Assembly outside lib folder.
WARNING: Description: The assembly 'lib/net35\NCalc.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
WARNING: Solution: Move it into the 'lib' folder if it should be referenced.
``

**Comment by pitermarx** [comment]
I changed the path separator and the warning disapeared
I think it's this issue https://github.com/NuGet/NuGet.Client/pull/1609
try this now https://ci.appveyor.com/project/pitermarx/ncalc-edge/build/1.4.4-build0001/artifacts

**Comment by pitermarx** [comment]
closed due to inactivity
