### ISSUE TITLE
Why is `OriginalExpression` not public?

### ISSUE THREAD

**Issue by eltechnic0** [pitermarx/NCalc-Edge#19]

**Comment by pitermarx** [comment]
No idea. Do you have a use case for it? Not fond of changing the public API

**Comment by eltechnic0** [comment]
For reference purposes. To be able to display the original string to the user easily, without any processing required. 

I understand it is not critical, but would be nice to have, no?

**Comment by pitermarx** [comment]
Looking at the code, what makes sense to me is to make it private readonly.
If you want it public you can just do this.

```
class Formula : Expression
{
	public new string OriginalExpression => base.OriginalExpression;
        ...
}
```
