### ISSUE TITLE
Division by 0?

### ISSUE THREAD

**Issue by ZioMick** [pitermarx/NCalc-Edge#21]
New to NCalc, testing basic functionalities but when I've tried this expression
**"10 / 0"**
surprisingly the result evaluated to "**8**"...

Did I miss something?

**Comment by pitermarx** [comment]
can you provide a code sample or Unit test with this result?

**Comment by ZioMick** [comment]
Here is the main "Program" (console application) I've used to test some functionality. Some of the formulas are taken directly from the main source code, I've added a couple of formulas with one direct division by zero and one with two parameters that are set to "7" and "0" before evaluation. I've attached also an image with the console results.

    class Program
    {
        static void Main(string[] args)
        {
            var expressions = new[]
            {
                "0 / 10",
                "2 * (3 + 5)",
                "2 * (2*(2*(2+1)))",
                "10 % 3",
                "false || not (false and true)",
                "3 > 2 and 1 <= (3-2)",
                "3 % 2 != 10 % 3",
                "[A] + [B]",
                "10 + 3 * 4",
                "7 == 7",
                "5 / 0",  //odd result
                "[X] / [Y]"  //odd result
            };
            
            foreach (string expression in expressions)
            {
                Expression myExpr = new Expression(expression);
                
                if (expression.Contains("[A]"))
                {
                    myExpr.Parameters["A"] = "I am running";
                }
                
                if (expression.Contains("[B]"))
                {
                    myExpr.Parameters["B"] = " along the road";                    
                }
                                
                if (expression.Contains("[X]"))
                {
                    myExpr.Parameters["X"] = 7;                    
                }
                                
                if (expression.Contains("[Y]"))
                {
                    myExpr.Parameters["Y"] = 0;                    
                }
               
                Console.WriteLine($"{expression} => {myExpr.Evaluate()}");
                
                if (myExpr.Parameters.Count > 0)
                {
                    foreach (KeyValuePair<string, object> myExprParameter in myExpr.Parameters)
                    {
                        Console.WriteLine($"  Parameter {myExprParameter.Key} => {myExprParameter.Value.ToString()}");
                    }
                }
            }
            
            Console.ReadKey(true);
        }
    }
![Console_Result](https://user-images.githubusercontent.com/50144740/57065479-d63c1980-6cc9-11e9-9bea-a14a8fe6f692.jpg)

**Comment by pitermarx** [comment]
Stupid question. Is it possible that the eight is really an infinity symbol and it is showing wrong?

**Comment by pitermarx** [comment]
https://dotnetfiddle.net/qrfQPQ

**Comment by ZioMick** [comment]
In fact you are right :)
looking at the "real" result of the evaluation through the watch window the evaluation states "infinity"

I didn't think to look here... sorry :)

Thanks for you patience,
All the best

![Infinity](https://user-images.githubusercontent.com/50144740/57066639-0638ec00-6ccd-11e9-9a60-9d1d164a88d1.jpg)
