### ISSUE TITLE
Power operator?

### ISSUE THREAD

**Issue by DaveMartel** [pitermarx/NCalc-Edge#24]
The wiki (operators page) mentions "Power" as a possible operator or operator type. The standard notation for power as far as I understand it elsewhere would be '^'. However '^' is used as the operator for bitwise or. After mentioning that power is possible, there is nothing further as to what the actual operator is.

I know there is Power (x, y) in the functions. 

It is just that I am fairly confident that my users are going to expect to type (x^2) to square a number and I have check that the evaluator does in fact do a bit wise or of 2 against x.

Thanks for any enlightenment.

**Comment by pitermarx** [comment]
the power is done via the function POW
https://github.com/pitermarx/NCalc-Edge/wiki/Functions
![imagem](https://user-images.githubusercontent.com/3081298/62688921-b51e4f80-b9c1-11e9-9842-8548c676eb5d.png)

^ is the operator for bitwise xor
https://github.com/pitermarx/NCalc-Edge/wiki/Operators

I'll investigate if there is a power operator, or if it is a bug in the wiki

**Comment by pitermarx** [comment]
^ is the operator for bitwise xor

**Comment by pitermarx** [comment]
After reading the code, I think this is a bug in the wiki. I'll remove it. Thanks for the warning

**Comment by DaveMartel** [comment]
Thanks. I understand that ^ is the operator for bitwise xor. 

My biggest issue is going to be the fact my users are used to ^ being the power operator and I am pretty sure they are going to try and use it that way. Now got to work out how to warn them, or override what they type... :-)

**Comment by AlizerUncaged** [comment]
is there any way to override the ^ operator? my end users will be typing ^ not `Power`

**Comment by pitermarx** [comment]
no, I don't think there is
