### ISSUE TITLE
Need extensibility for the Evaluation Visitor

### ISSUE THREAD

**Issue by shahjeet297** [pitermarx/NCalc-Edge#26]
I would like to make some changes to EvaluationVisitor and add ^ sysmbol for power function rather than pow. Currently the method is overridable but when we use the ExpressionEvaluator in the Expression class we can not inject any other class as it is hard coded there.

I did some changes in the pull request #25 to achieve the same. Can you merge these changes to master and provide the new release for the same.

**Comment by pitermarx** [comment]
I will not add these as I'm not supporting this anymore
