### ISSUE TITLE
Switch to NUnit?

### ISSUE THREAD

**Issue by tmenier** [pitermarx/NCalc-Edge#5]
I'll do a PR for this but I wanted to run it by you first. (i.e. make sure it's convenient and you're already tooled to run NUnit tests, such as with R#)

I don't get religious about test frameworks, but NUnit's [TestCase attribute](https://github.com/nunit/docs/wiki/TestCase-Attribute) would be extremely handy to have for some of my recent tests and others. MSTest doesn't have an equivalent. Would you be ok with that switch? This one wouldn't touch the actual library code, obviously.

**Comment by pitermarx** [comment]
Go for it

**Comment by pitermarx** [comment]
I did it
